builds:
  - binary: chip8
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
    overrides:
      - goos: darwin
        env:
          - CGO_ENABLED=0
archives:
  - format_overrides:
      - goos: windows
        format: zip
