name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -o windows/chip8.exe -v .

      - name: Go Test
        run: go test -v ./...

      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: windows/

  build-mac:
    runs-on: macos-latest
    env:
      GO111MODULE: "on"
      CGO_ENABLED: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -o mac/chip8 -v .

      - name: Go Test
        run: go test -v ./...

      - uses: actions/upload-artifact@v4
        with:
          name: mac
          path: mac/

  build-linux:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      CGO_ENABLED: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt install -y libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config
          go get ./...

      - name: Build
        run: go build -o linux/chip8 -v .

      - name: Go Test
        run: go test -v ./...

      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: linux/

  release:
    # if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-windows
      - build-mac
      - build-linux
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/
            windows/
            mac/
